# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

In [3]:
x=np.arange(10)

In [16]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [37]:
x=np.arange(10)
x=x.reshape(2,5)

y=np.full((2, 5), 1)

In [40]:
np.vstack((x,y))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### How to stack two arrays horizontally?

#### Desired Output::

In [41]:
x=np.arange(10)
x=x.reshape(2,5)
y=np.full((2,5),1)

In [44]:
np.hstack((x,y))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [49]:
x=np.arange(10)
y=x.reshape(2,5)

In [50]:
x=y.ravel()

In [51]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [53]:
a=np.arange(15)
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [54]:
a.reshape(15,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [62]:
a=np.arange(15)
b=b.reshape(5,3)

In [63]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [66]:
a=np.arange(25)
b=a.reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
np.power(b,2)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [70]:
a=np.arange(30)
b=a.reshape(5,6)
b.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [75]:
np.std(b)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [81]:
np.median(b)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [80]:
b.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [84]:
a=np.arange(16)
a=a.reshape(4,4)
np.diagonal(a) 


array([ 0,  5, 10, 15])

## Question:13

### Find the determinant of the previous array in Q12?

In [87]:
np.linalg.det(a)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [92]:
a=np.arange(15)
np.percentile(a,5)


0.7000000000000001

In [93]:
np.percentile(a,95)

13.299999999999999

## Question:15

### How to find if a given array has any null values?

In [94]:
a=np.arange(10)

In [98]:
np.isnan(a)

array([False, False, False, False, False, False, False, False, False,
       False])