# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [5]:
x=np.arange(10,50)

4. Find the shape of previous array in question 3

In [6]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [7]:
x.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [8]:
print(np.__version__)

print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/anaconda\\Library\\include']
None


7. Print the dimension of the array in question 3


In [9]:
x.ndim

1

8. Create a boolean array with all the True values

In [10]:
arroftrue=np.ones((5), dtype=bool)

9. Create a two dimensional array




In [11]:
twod=np.ones((2,2))

10. Create a three dimensional array



In [12]:
threeD=np.ones((2,2,3))

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [13]:
b=[1,2,3,4,5,6]
c=b[::-1]
c

[6, 5, 4, 3, 2, 1]

12. Create a null vector of size 10 but the fifth value which is 1 

In [15]:
arr=np.zeros(10)
arr
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [16]:
identity=np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [17]:
arrint = np.array([1, 2, 3, 4, 5])
arrint = arr. astype('float64')
arrint.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [19]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])


Make an array by comparing both the arrays provided above

In [20]:
comparison = arr1 == arr2
comparison.all()

False

17. Extract all odd numbers from arr with values(0-9)

In [21]:
a = np.array([1,2,3,4,5,6,6,7,7,8,9])
np.where(a%2==1,-1,a)

array([-1,  2, -1,  4, -1,  6,  6, -1, -1,  8, -1])

18. Replace all odd numbers to -1 from previous array

In [22]:
np.where(a%2==1,-1,a)

array([-1,  2, -1,  4, -1,  6,  6, -1, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [23]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [24]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [25]:
 arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

    
np.where(arr2d==5,12,arr2d)

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [27]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d[1]=64
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[64, 64, 64],
        [64, 64, 64]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [28]:
x = np.array([[1, 2, 3,4,5], [6,7,8,9,10]], np.int32)

x[:1]

x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [29]:

x=np.arange(10)
y=x.reshape(2,5)
z=y[::,1]
z

array([1, 6])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [30]:
x=np.arange(10)
y=x.reshape(2,5)
z=y[::,1]
z

array([1, 6])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [32]:
x = np.random.random((5,5))
np.amax(x)


0.9791913112022753

In [33]:
np.amin(x)

0.04586341255266324

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [34]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np. intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [35]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.where(names=='Will')

(array([2, 4], dtype=int64),)

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [37]:
np.where(names=='Will')
np.where(names=='Joe')

(array([1, 5, 6], dtype=int64),)

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [38]:
q=np.arange(15)
q.reshape(5,3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [40]:
w=np.arange(16)
e=w.reshape(2,2,4)
e

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

33. Swap axes of the array you created in Question 32

In [41]:
np.swapaxes(e,0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [42]:
x=np.arange(10)
sqr=np.sqrt(x)
np.where(sqr<0.5,0,sqr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [43]:
x=np.random.randn(12)
y=np.random.randn(12)
z=np.maximum(x,y)
z

array([-0.04437308,  1.10228628, -1.45752637,  0.57625395, -0.82412853,
        0.81077804, -0.64310721, -0.21137563,  2.02397424,  1.96905947,
       -1.04406684, -0.64567716])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [44]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [45]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
result

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [47]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[0:1]=newColumn
sampleArray

array([[10, 10, 10],
       [82, 22, 12],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [48]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z=np.dot(x,y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [50]:
x=np.random.rand(4,5) 
x.cumsum()

array([0.64476614, 0.85910442, 1.07650282, 1.53106507, 1.78751415,
       2.0375971 , 2.66399918, 2.87481081, 3.69932321, 4.38911342,
       4.68156733, 4.74971725, 5.42534742, 5.92856941, 5.97400884,
       6.1887335 , 6.22277047, 6.58597215, 6.8537941 , 7.32587818])